---
# Optional method of pinning a specific version of Jenkins and/or overriding the
# default Jenkins packaging URL.
# jenkins_version: "1.644"
# jenkins_pkg_url: "https://www.example.com"

# Change this to `latest` to update Jenkins if a newer version is available.
jenkins_package_state: present

jenkins_connection_delay: 5
jenkins_connection_retries: 60
jenkins_home: /var/lib/jenkins
jenkins_hostname: localhost
jenkins_http_port: 8080
jenkins_jar_location: /var/lib/jenkins/updates/jenkins-cli.jar
jenkins_url_prefix: ""
jenkins_java_options: "-Djenkins.install.runSetupWizard=false"

jenkins_plugins: [simple-theme-plugin, ace-editor, git-client, mailer, plain-credentials, workflow-basic-steps, ant, git-server, mapdb-api, resource-disposer, workflow-cps-global-lib, antisamy-markup-formatter, git, matrix-auth, scm-api, workflow-cps, bouncycastle-api, github-api, matrix-project, script-security, workflow-durable-task-step, branch-api, github-branch-source, momentjs, ssh-credentials, workflow-job, build-timeout, github-organization-folder, pam-auth, ssh-slaves, workflow-multibranch, cloudbees-folder, github, pipeline-build-step, structs, workflow-scm-step, credentials-binding, gradle, pipeline-graph-analysis, subversion, workflow-step-api, credentials, handlebars, pipeline-input-step, timestamper, workflow-support, display-url-api, icon-shim, pipeline-milestone-step, token-macro, ws-cleanup, durable-task, jquery-detached, pipeline-rest-api, windows-slaves, email-ext, junit, pipeline-stage-step, workflow-aggregator, external-monitor-job, ldap, pipeline-stage-view, workflow-api]
jenkins_plugins_state: latest

jenkins_plugin_updates_expiration: 86400
jenkins_plugin_timeout: 30
jenkins_plugins_install_dependencies: true
jenkins_updates_url: "https://updates.jenkins.io"

jenkins_admin_username: admin
jenkins_admin_password: mariano 
jenkins_admin_password_file: ""

jenkins_process_user: jenkins
jenkins_process_group: "{{ jenkins_process_user }}"

jenkins_init_changes:
  - option: "JENKINS_ARGS"
    value: "--prefix={{ jenkins_url_prefix }}"
  - option: "{{ jenkins_java_options_env_var }}"
    value: "{{ jenkins_java_options }}"
