---
- name: adding mongodb gpg key
  apt_key:
    url: https://www.mongodb.org/static/pgp/server-4.2.asc
    state: present
  become: true

- name: install mongodb deb repository
  become: true
  apt_repository:
    repo: deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.2 multiverse
    state: present

- name: update repositories cache and install mongodb-org package
  become: yes
  apt:
    name: mongodb-org
    update_cache: yes

- name: start service mongod
  become: true
  service:
    name: mongod
    state: started

#- name: start service mongod
#  become: true
#  service:
#    name: mongod
#    state: started

# wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | apt-key add -
