---
# tasks file for software base

# fixing issue for local lang environment
- name: fixing issue for local lang environment
  shell: |
    sh -c "echo 'LC_ALL=en_US.UTF-8\nLANG=en_US.UTF-8' > /etc/environment"
    sh -c "echo 'LC_ALL=en_US.UTF-8\nLANG=en_US.UTF-8' > /etc/default/locale"

# update apt cache
- name: update apt cache
  apt: update_cache=yes

# upgrade all packages
#- name: upgrade all packages
#  apt: upgrade=dist

# install software base
- name: install software base
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - sudo
    - acl
    - build-essential
    - iputils-ping
    - net-tools
    - wget
    - curl
    - unzip
    - git
    - less
    - vim
    - apt-transport-https
    - maven
    - expect
    - xvfb
    - jq

